package store

import (
	"crypto/rand"
	"encoding/base32"
	"strings"
)

// idEncoding spells an id without padding, so 12 random bytes become exactly
// 20 characters.
var idEncoding = base32.StdEncoding.WithPadding(base32.NoPadding)

// NewID returns a fresh identifier for any row in the database: 20 lowercase
// base32 characters carrying 96 bits of randomness. Ids are text everywhere
// so that they can be generated by the harness before a row exists, copied
// into container names and URLs, and read aloud in a log line.
func NewID() string {
	var b [12]byte
	// crypto/rand.Read fills b completely or crashes the program; it cannot
	// return an error.
	_, _ = rand.Read(b[:])
	return strings.ToLower(idEncoding.EncodeToString(b[:]))
}
